package com.example.resumeats.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.Builder;

/**
 * A single resume correction suggestion generated by the LLM.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
public class Correction {

    /** The resume section this correction applies to (e.g., "Summary", "Skills"). */
    private String section;

    /** The current text or situation in the resume. */
    private String current;

    /** The suggested improved version. */
    private String suggested;

    /** The reason why this correction is recommended. */
    private String reason;
}
